[default]
profile=gpu-hq
gpu-api=vulkan
gpu-context=x11vk
spirv-compiler=auto
hwdec=no
video-sync=audio
scale=ewa_lanczos
cscale=ewa_lanczos
audio-display=no
audio-channels=stereo
af=lavfi=[dynaudnorm=g=15]
alang=jpn,ja,eng,en
