[default]
profile=opengl-hq
hwdec=no
scale=ewa_lanczossharp
cscale=ewa_lanczossharp
interpolation
tscale=oversample
video-sync=display-resample-vdrop
audio-display=no
ytdl-format=[protocol!=http_dash_segments]
