"ui.background" = { bg = "base" }
"ui.cursor" = { fg = "rose", modifiers = ["reversed"] }
"ui.cursor.match" = { fg = "gold", modifiers = ["underlined"] }
"ui.cursor.primary" = { fg = "rose", modifiers = ["reversed"] }
"ui.linenr" = { fg = "subtle" }
"ui.linenr.selected" = "highlightOverlay"
"ui.statusline" = { fg = "foam", bg = "surface" }
"ui.statusline.inactive" = { fg = "iris", bg = "surface" }
"ui.popup" = { bg = "surface" }
"ui.popup.info" = { bg = "surface" }
"ui.window" = { bg = "base" }
"ui.help" = { bg = "overlay", fg = "foam" }
"ui.text" = { fg = "text" }
"ui.text.focus" = { fg = "foam", modifiers = ["bold"]}
"ui.text.info" = { fg = "pine", modifiers = ["bold"]}
"ui.virtual" = { fg = "higlight" }
"ui.virtual.ruler" = { bg = "surface" }
"ui.menu" = { fg = "text", bg = "overlay" }
"ui.menu.selected" = { fg = "iris", bg = "surface" }
"ui.selection" = { bg = "highlightOverlay" }

"type" = "foam"
"type.builtin" = "foam"
"constructor" = "gold"
"constant" = "gold"
"string" = "gold"
"comment" = "subtle"
"variable" = "text"
"label" = "iris"
"punctuation" = "text"
"keyword" = "pine"
"operator" = "rose"
"function" = "rose"
"function.builtin" = "rose"
"function.method" = "foam"
"tag" = "iris"
"namespace" = "pine"

"diff.plus" = "foam"
"diff.delta" = "rose"
"diff.minus" = "love"

"info" = "gold"
"hint" = "gold"
"debug" = "rose"
"diagnostic" = "rose"
"error" = "love"

"markup.heading.marker" = "subtle"
"markup.heading.1" = { fg = "gold", modifiers = ["bold"] }
"markup.heading.2" = { fg = "iris", modifiers = ["bold"] }
"markup.heading.3" = { fg = "love", modifiers = ["bold"] }
"markup.heading.4" = { fg = "pine", modifiers = ["bold"] }
"markup.heading.5" = { fg = "rose", modifiers = ["bold"] }
"markup.heading.6" = { fg = "foam", modifiers = ["bold"] }
"markup.list" = { fg = "love" }
"markup.bold" = { fg = "gold", modifiers = ["bold"] }
"markup.italic" = { fg = "iris", modifiers = ["italic"] }
"markup.link.url" = { fg = "pine", modifiers = ["underlined"]}
"markup.link.text" = { fg = "foam" }
"markup.quote" = { fg = "rose" }
"markup.raw" = { fg = "foam" }

[palette]
base     = "#232136" 
surface  = "#2a273f" 
overlay  = "#393552"
inactive = "#59546d"
subtle   = "#817c9c"
text     = "#e0def4"
love     = "#eb6f92"
gold     = "#f6c177"
rose     = "#ea9a97"
pine     = "#3e8fb0"
foam     = "#9ccfd8"
iris     = "#c4a7e7"
highlight = "#312f44"
highlightInactive = "#2a283d"
highlightOverlay = "#3f3c53"
